
include ../calib.mk
include $(ROOT_DIR)/config.mk


UNITTEST_TARGETS = sys_info build_info

sys_info_NAME=test_sys_info
sys_info_SRCS=test_sys_info.c
sys_info_LIBS=calib


build_info_NAME=test_build_info
build_info_SRCS=test_build_info.c
build_info_LIBS=calib


include $(ROOT_DIR)/template.mk

